/** @type {import('next').NextConfig} */
const nextConfig = {
  // Skip TS errors from legacy Figma components during build
  typescript: { ignoreBuildErrors: true },

  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '*.supabase.co' },
    ],
  },

  async redirects() {
    return [
      // ── Garbage URLs ──
      { source: '/%24', destination: '/', permanent: true },
      { source: '/%26', destination: '/', permanent: true },
      { source: '/sitemap', destination: '/', permanent: true },

      // NOTE: uppercase ticker redirects removed — Next.js routes are case-insensitive
      // (caseSensitive:false in routes-manifest) so /USDC→/usdc was creating a redirect
      // loop: /usdc matched /USDC case-insensitively and redirected to itself forever.

      // ── Invalid network slugs ──
      { source: '/cbbtc/eth', destination: '/cbbtc', permanent: true },
      { source: '/eurc/eth', destination: '/eurc', permanent: true },
      { source: '/eurc/ethereum', destination: '/eurc', permanent: true },
      { source: '/usdc/eth', destination: '/usdc', permanent: true },
      { source: '/usdt/eth', destination: '/usdt', permanent: true },
      { source: '/usdt/ethereum', destination: '/usdt', permanent: true },
      { source: '/wbtc/eth', destination: '/wbtc', permanent: true },
      { source: '/EURC/Avalanche', destination: '/eurc', permanent: true },

      // ── Old network slug ──
      { source: '/usdc/bnb-chain', destination: '/usdc/bnb', permanent: true },

      // ── Old format: /{ticker}/{network}/{product} → /vault/{new-slug} ──
      // Wave 1
      { source: '/usdc/arbitrum/harvest-dolomite-autocompounder', destination: '/vault/usdc-dolomite-autocompounder-harvest-arbitrum', permanent: true },
      { source: '/usdc/arbitrum/morpho-ultrayield-usdc-(edge-capital)', destination: '/vault/usdc-ultrayield-morpho-edge-capital-arbitrum', permanent: true },
      { source: '/usdc/avalanche/euler-usdc---k3-capital-cluster', destination: '/vault/usdc-cluster-euler-k3-capital-avalanche', permanent: true },
      { source: '/usdc/avalanche/folks-finance-lending-market', destination: '/vault/usdc-lending-market-folks-finance-avalanche', permanent: true },
      { source: '/usdc/base/beefy-compound-v3-autocompounder', destination: '/vault/usdc-compound-v3-autocompounder-beefy-base', permanent: true },
      { source: '/usdc/base/harvest-arcadia-autocompounder', destination: '/vault/usdc-arcadia-autocompounder-harvest-base', permanent: true },
      { source: '/usdc/base/harvest-autopilot', destination: '/vault/usdc-autopilot-harvest-base', permanent: true },
      { source: '/usdc/base/morpho-high-yield-usdc-(clearstar)', destination: '/vault/usdc-high-yield-morpho-clearstar-base', permanent: true },
      { source: '/usdc/base/morpho-universal-usdc-(re7-labs)', destination: '/vault/usdc-universal-morpho-re7-base', permanent: true },
      { source: '/usdc/ethereum/maple-test-test-earn-maple', destination: '/vault/usdc-earn-maple-mainnet', permanent: true },
      { source: '/usdc/mainnet/euler-euler-prime-(eulerdao)', destination: '/vault/usdc-euler-prime-eulerdao-mainnet', permanent: true },
      { source: '/usdc/mainnet/euler-openeden-usdc-(ouroboros-capital)', destination: '/vault/usdc-openeden-euler-ouroboros-capital-mainnet', permanent: true },
      { source: '/usdc/mainnet/lagoon-autonomous-liquidity-usd-(almanak)', destination: '/vault/usdc-autonomous-liquidity-usd-lagoon-almanak-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-blue-chip-usdc-vault-(sparkdao)', destination: '/vault/usdc-blue-chip-vault-morpho-sparkdao-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-swissborg-usdc-(gauntlet)', destination: '/vault/usdc-swissborg-morpho-gauntlet-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-tac-usdc-(9summits)', destination: '/vault/usdc-core-morpho-9summits-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-vault-bridge-usdc-(steakhouse)', destination: '/vault/usdc-vault-bridge-morpho-steakhouse-mainnet', permanent: true },
      { source: '/usdc/mainnet/yearn-morpho-steakhouse-usdc-compounder', destination: '/vault/usdc-morpho-steakhouse-compounder-yearn-mainnet', permanent: true },
      // Wave 2
      { source: '/usdc/arbitrum/fluid-lend', destination: '/vault/usdc-lend-fluid-arbitrum', permanent: true },
      { source: '/usdc/arbitrum/morpho-usdc-reactor-(clearstar)', destination: '/vault/usdc-reactor-morpho-clearstar-arbitrum', permanent: true },
      { source: '/usdc/arbitrum/morpho-usdc-yield-(kpk)', destination: '/vault/usdc-yield-morpho-kpk-arbitrum', permanent: true },
      { source: '/usdc/avalanche/euler-usdc---re7-labs-cluster', destination: '/vault/usdc-cluster-euler-re7-avalanche', permanent: true },
      { source: '/usdc/base/avantis-earn---avusdc', destination: '/vault/usdc-earn-avusdc-avantis-base', permanent: true },
      { source: '/usdc/base/euler-euler-base', destination: '/vault/usdc-euler-base', permanent: true },
      { source: '/usdc/base/lagoon-core-usdc-(detrade)', destination: '/vault/usdc-core-lagoon-detrade-base', permanent: true },
      { source: '/usdc/base/morpho-prime-usdc-(gauntlet)', destination: '/vault/usdc-prime-morpho-gauntlet-base', permanent: true },
      { source: '/usdc/base/morpho-pyth-usdc-(re7-labs)', destination: '/vault/usdc-pyth-morpho-re7-base', permanent: true },
      { source: '/usdc/base/morpho-resolv-usdc-(apostro)', destination: '/vault/usdc-resolv-morpho-apostro-base', permanent: true },
      { source: '/usdc/base/morpho-seamless-usdc-(gauntlet)', destination: '/vault/usdc-seamless-morpho-gauntlet-base', permanent: true },
      { source: '/usdc/base/morpho-usdc-core-(gauntlet)', destination: '/vault/usdc-core-morpho-gauntlet-base', permanent: true },
      { source: '/usdc/base/morpho-usdc-vault-(apostro)', destination: '/vault/usdc-vault-morpho-apostro-base', permanent: true },
      { source: '/usdc/base/morpho-usdc-vault-(sparkdao)', destination: '/vault/usdc-vault-morpho-sparkdao-base', permanent: true },
      { source: '/usdc/base/morpho-yearn-og-usdc', destination: '/vault/usdc-og-morpho-yearn-base', permanent: true },
      { source: '/usdc/base/yearn-mopho-moonwell-flagship-usdc-compounder', destination: '/vault/usdc-mopho-moonwell-flagship-compounder-yearn-base', permanent: true },
      { source: '/usdc/mainnet/aave-v3', destination: '/vault/usdc-v3-aave-mainnet', permanent: true },
      { source: '/usdc/mainnet/euler-resolv-usdc-(tulipa)', destination: '/vault/usdc-resolv-euler-tulipa-mainnet', permanent: true },
      { source: '/usdc/mainnet/euler-swaap-lend', destination: '/vault/usdc-swaap-lend-euler-mainnet', permanent: true },
      { source: '/usdc/mainnet/fluid-lend', destination: '/vault/usdc-lend-fluid-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-steakhouse-usdc-rwa', destination: '/vault/usdc-rwa-morpho-steakhouse-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-usdc-prime-(kpk)', destination: '/vault/usdc-prime-morpho-kpk-mainnet', permanent: true },
      { source: '/usdc/mainnet/morpho-usdc-prime-(re7)', destination: '/vault/usdc-prime-morpho-re7-mainnet', permanent: true },

      // ── Old vault slugs (missing network suffix or wrong word order) ──
      // Wave 1
      { source: '/vault/cbbtc-cbbtc-market-radiant-v2', destination: '/vault/cbbtc-market-radiant-v2-base', permanent: true },
      { source: '/vault/eth-morpho-yearn-og-weth-compounder-yearn', destination: '/vault/eth-morpho-yearn-og-weth-compounder-mainnet', permanent: true },
      { source: '/vault/eth-weth-lend-fluid', destination: '/vault/eth-weth-lend-fluid-mainnet', permanent: true },
      { source: '/vault/eth-weth-lend-pool-arcadia', destination: '/vault/eth-weth-lend-pool-arcadia-base', permanent: true },
      { source: '/vault/eth-weth-spark', destination: '/vault/eth-weth-spark-mainnet', permanent: true },
      { source: '/vault/eth-wsteth-aave', destination: '/vault/eth-wsteth-aave-mainnet', permanent: true },
      { source: '/vault/eth-wsteth-spark', destination: '/vault/eth-wsteth-spark-mainnet', permanent: true },
      { source: '/vault/eurc-core-vault-yo', destination: '/vault/eurc-core-vault-yo-base', permanent: true },
      { source: '/vault/usdc-apostro-euler-apostro', destination: '/vault/usdc-apostro-euler-bnb', permanent: true },
      { source: '/vault/usdc-degen-usdc-morpho-yearn', destination: '/vault/usdc-degen-morpho-yearn-arbitrum', permanent: true },
      { source: '/vault/usdc-earn-avusdc-avantis', destination: '/vault/usdc-earn-avusdc-avantis-base', permanent: true },
      { source: '/vault/usdc-high-yield-usdc-morpho-steakhouse', destination: '/vault/usdc-high-yield-morpho-steakhouse-base', permanent: true },
      { source: '/vault/usdc-private-credit-wildcat-hyperithm', destination: '/vault/usdc-private-credit-wildcat-hyperithm-mainnet', permanent: true },
      { source: '/vault/usdc-srusd-leveraged-looping-ipor-fusion-reservoir', destination: '/vault/usdc-srusd-ipor-fusion-reservoir-mainnet', permanent: true },
      { source: '/vault/usdc-swissborg-usdc-morpho-gauntlet', destination: '/vault/usdc-swissborg-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-universal-usdc-morpho-re7', destination: '/vault/usdc-universal-morpho-re7-base', permanent: true },
      { source: '/vault/usdc-usdc-autopilot-harvest', destination: '/vault/usdc-autopilot-harvest-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-cluster-euler-k3-capital', destination: '/vault/usdc-cluster-euler-k3-capital-avalanche', permanent: true },
      { source: '/vault/usdc-usdc-morpho-mev-capital', destination: '/vault/usdc-morpho-mev-capital-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-rwa-morpho-steakhouse', destination: '/vault/usdc-rwa-morpho-steakhouse-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-august-digital-morpho', destination: '/vault/usdc-vault-morpho-august-digital-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-hyperithm', destination: '/vault/usdc-vault-morpho-hyperithm-arbitrum', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-pangolins', destination: '/vault/usdc-vaults-morpho-pangolins-base', permanent: true },
      { source: '/vault/usdt-flagship-usdt-morpho-b-protocol', destination: '/vault/usdt-flagship-morpho-b-protocol-mainnet', permanent: true },
      { source: '/vault/usdt-wintermute-trading-private-credit-wildcat', destination: '/vault/usdt-wintermute-trading-private-credit-wildcat-mainnet', permanent: true },
      { source: '/vault/wbtc-wbtc-market-spark', destination: '/vault/wbtc-market-spark-mainnet', permanent: true },
      // Wave 2
      { source: '/vault/cbbtc-usdc-market-aave', destination: '/vault/cbbtc-usdc-market-aave-mainnet', permanent: true },
      { source: '/vault/eth-cbeth-euler-base-euler-gauntlet', destination: '/vault/eth-cbeth-euler-base-gauntlet', permanent: true },
      { source: '/vault/eth-extrafi-autocompounder-harvest', destination: '/vault/eth-extrafi-autocompounder-harvest-base', permanent: true },
      { source: '/vault/eth-morpho-gauntlet-weth-prime-compounder-yearn-v2', destination: '/vault/eth-morpho-gauntlet-weth-prime-compounder-yearn-v2-mainnet', permanent: true },
      { source: '/vault/eth-seamless-weth-autocompounder-beefy', destination: '/vault/eth-seamless-weth-autocompounder-beefy-base', permanent: true },
      { source: '/vault/eth-weeth-euler-base-euler-gauntlet', destination: '/vault/eth-weeth-euler-base-gauntlet', permanent: true },
      { source: '/vault/eth-weth-core-vault-2-yearn-v2', destination: '/vault/eth-weth-core-vault-2-yearn-v2-mainnet', permanent: true },
      { source: '/vault/eth-weth-euler-prime-euler-gauntlet', destination: '/vault/eth-weth-euler-prime-gauntlet-mainnet', permanent: true },
      { source: '/vault/eth-weth-lending-fluid', destination: '/vault/eth-weth-lending-fluid-base', permanent: true },
      { source: '/vault/eth-wsteth-looping-ipor-fusion', destination: '/vault/eth-wsteth-looping-ipor-fusion-base', permanent: true },
      { source: '/vault/usdc-40-acres-autocompounder-harvest', destination: '/vault/usdc-40-acres-autocompounder-harvest-base', permanent: true },
      { source: '/vault/usdc-apostro-resolv-euler', destination: '/vault/usdc-resolv-euler-apostro-mainnet', permanent: true },
      { source: '/vault/usdc-autonomous-liquidity-usd-lagoon-almanak', destination: '/vault/usdc-autonomous-liquidity-usd-lagoon-almanak-mainnet', permanent: true },
      { source: '/vault/usdc-derivatives-pool-ipor-fusion', destination: '/vault/usdc-derivatives-pool-ipor-fusion-mainnet', permanent: true },
      { source: '/vault/usdc-euler-arbitrum-yield-euler-gauntlet', destination: '/vault/usdc-euler-arbitrum-yield-gauntlet', permanent: true },
      { source: '/vault/usdc-euler-prime-euler-eulerdao', destination: '/vault/usdc-euler-prime-eulerdao-mainnet', permanent: true },
      { source: '/vault/usdc-frontier-usdc-vault-mev-capital-morpho', destination: '/vault/usdc-frontier-vault-morpho-mev-capital-base', permanent: true },
      { source: '/vault/usdc-frontier-usdc-vault-morpho-mev-capital', destination: '/vault/usdc-frontier-vault-morpho-mev-capital-base', permanent: true },
      { source: '/vault/usdc-fusion-lending-optimizer-ipor-fusion', destination: '/vault/usdc-fusion-lending-optimizer-ipor-base', permanent: true },
      { source: '/vault/usdc-high-yield-usdc-clearstar-morpho', destination: '/vault/usdc-high-yield-morpho-clearstar-base', permanent: true },
      { source: '/vault/usdc-high-yield-usdc-v1-1-morpho-steakhouse', destination: '/vault/usdc-high-yield-v1-1-morpho-steakhouse-base', permanent: true },
      { source: '/vault/usdc-high-yield-usdc-v1-1-steakhouse-morpho', destination: '/vault/usdc-high-yield-v1-1-morpho-steakhouse-base', permanent: true },
      { source: '/vault/usdc-market-moonwell', destination: '/vault/usdc-market-moonwell-base', permanent: true },
      { source: '/vault/usdc-mopho-moonwell-flagship-usdc-compounder-yearn', destination: '/vault/usdc-mopho-moonwell-flagship-compounder-yearn-base', permanent: true },
      { source: '/vault/usdc-og-usdc-morpho-yearn', destination: '/vault/usdc-og-morpho-yearn-mainnet', permanent: true },
      { source: '/vault/usdc-pyth-usdc-morpho-re7', destination: '/vault/usdc-pyth-morpho-re7-base', permanent: true },
      { source: '/vault/usdc-reservoir-srusd-leveraged-looping-ipor', destination: '/vault/usdc-srusd-ipor-fusion-reservoir-mainnet', permanent: true },
      { source: '/vault/usdc-resolv-euler-apostro', destination: '/vault/usdc-resolv-euler-apostro-mainnet', permanent: true },
      { source: '/vault/usdc-resolv-usdc-apostro-euler', destination: '/vault/usdc-resolv-euler-apostro-base', permanent: true },
      { source: '/vault/usdc-resolv-usdc-morpho-gauntlet', destination: '/vault/usdc-resolv-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-stablecoin-maxi-euler-re7', destination: '/vault/usdc-stablecoin-maxi-euler-re7-mainnet', permanent: true },
      { source: '/vault/usdc-turtle-avalanche-usdc-lagoon-9summits', destination: '/vault/usdc-turtle-avalanche-lagoon-9summits', permanent: true },
      { source: '/vault/usdc-turtle-usdc-morpho-9summits', destination: '/vault/usdc-turtle-morpho-9summits-mainnet', permanent: true },
      { source: '/vault/usdc-ultrayield-usdc-edge-capital-morpho', destination: '/vault/usdc-ultrayield-morpho-edge-capital-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-frontier-morpho-gauntlet', destination: '/vault/usdc-frontier-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-fusion-ipor', destination: '/vault/usdc-ipor-fusion-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-ipor-fusion', destination: '/vault/usdc-ipor-fusion-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-lending-optimizer-ipor-fusion-tesseract', destination: '/vault/usdc-lending-optimizer-ipor-fusion-tesseract-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-prime-kpk-morpho', destination: '/vault/usdc-prime-morpho-kpk-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-prime-morpho-kpk', destination: '/vault/usdc-prime-morpho-kpk-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-reactor-morpho-clearstar', destination: '/vault/usdc-reactor-morpho-clearstar-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-rwa-morpho-gauntlet', destination: '/vault/usdc-rwa-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-lagoon-excellion', destination: '/vault/usdc-vault-lagoon-excellion-avalanche', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-apostro', destination: '/vault/usdc-vault-morpho-apostro-base', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-sparkdao', destination: '/vault/usdc-vault-morpho-sparkdao-base', permanent: true },
      { source: '/vault/usdc-usdc-yield-morpho-kpk', destination: '/vault/usdc-yield-morpho-kpk-arbitrum', permanent: true },
      { source: '/vault/usdc-yousd-looper-ipor-fusion', destination: '/vault/usdc-yousd-looper-ipor-fusion-ethereum', permanent: true },
      { source: '/vault/usdt-deltausd-lagoon-smardex', destination: '/vault/usdt-deltausd-lagoon-smardex-mainnet', permanent: true },
      { source: '/vault/wbtc-pendle-wbtc-morpho-mev-capital', destination: '/vault/wbtc-pendle-morpho-mev-capital-mainnet', permanent: true },
      { source: '/vault/wbtc-reservoir-btc-yield-leveraged-looping-ipor-fusion', destination: '/vault/wbtc-btc-yield-ipor-fusion-reservoir-mainnet', permanent: true },
      { source: '/vault/wbtc-wbtc-pool-across-protocol', destination: '/vault/wbtc-pool-across-protocol-mainnet', permanent: true },

      // Wave 3 — GSC "Duplicate without user-selected canonical" report
      { source: '/vault/cbbtc-cbbtc-core-morpho-gauntlet', destination: '/vault/cbbtc-core-morpho-gauntlet-base', permanent: true },
      { source: '/vault/cbbtc-cbbtc-market-extrafi', destination: '/vault/cbbtc-market-extrafi-base', permanent: true },
      { source: '/vault/cbbtc-flagship-cbbtc-lagoon-tulipa-capital', destination: '/vault/cbbtc-flagship-lagoon-tulipa-capital-mainnet', permanent: true },
      { source: '/vault/eth-infinifi-eth-carry-ipor-fusion', destination: '/vault/eth-infinifi-carry-ipor-fusion-ethereum', permanent: true },
      { source: '/vault/eth-staking-product-meth-protocol', destination: '/vault/eth-staking-product-meth-protocol-mainnet', permanent: true },
      { source: '/vault/usdc-blue-chip-usdc-vault-morpho-sparkdao', destination: '/vault/usdc-blue-chip-vault-morpho-sparkdao-mainnet', permanent: true },
      { source: '/vault/usdc-cap-ecosystem-usdc-morpho-gauntlet', destination: '/vault/usdc-cap-ecosystem-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-compound-autocompounder-beefy', destination: '/vault/usdc-compound-autocompounder-beefy-arbitrum', permanent: true },
      { source: '/vault/usdc-cronos-usdc-ecosystem-morpho-steakhouse', destination: '/vault/usdc-cronos-ecosystem-morpho-steakhouse-mainnet', permanent: true },
      { source: '/vault/usdc-elixir-usdc-morpho-mev-capital', destination: '/vault/usdc-elixir-morpho-mev-capital-mainnet', permanent: true },
      { source: '/vault/usdc-euler-yield-euler-eulerdao', destination: '/vault/usdc-euler-yield-eulerdao-mainnet', permanent: true },
      { source: '/vault/usdc-extrafi-xlend-usdc-morpho-gauntlet', destination: '/vault/usdc-extrafi-xlend-morpho-gauntlet-base', permanent: true },
      { source: '/vault/usdc-f-protocol-morpho-re7-mainnet', destination: '/vault/usdc-f-x-protocol-morpho-re7-mainnet', permanent: true },
      { source: '/vault/usdc-fx-protocol-morpho-re7', destination: '/vault/usdc-f-x-protocol-morpho-re7-mainnet', permanent: true },
      { source: '/vault/usdc-gauntlet-usdc-frontier-morpho', destination: '/vault/usdc-frontier-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-high-yield-usdc-morpho-clearstar', destination: '/vault/usdc-high-yield-morpho-clearstar-base', permanent: true },
      { source: '/vault/usdc-infinifi-usdc-morpho-steakhouse', destination: '/vault/usdc-infinifi-morpho-steakhouse-mainnet', permanent: true },
      { source: '/vault/usdc-labs-cluster-euler-re7', destination: '/vault/usdc-cluster-euler-re7-avalanche', permanent: true },
      { source: '/vault/usdc-moonwell-autocompounder-harvest', destination: '/vault/usdc-moonwell-autocompounder-harvest-base', permanent: true },
      { source: '/vault/usdc-moonwell-flagship-b-protocol-morpho', destination: '/vault/usdc-moonwell-flagship-morpho-b-protocol-base', permanent: true },
      { source: '/vault/usdc-moonwell-flagship-morpho-b-protocol', destination: '/vault/usdc-moonwell-flagship-morpho-b-protocol-base', permanent: true },
      { source: '/vault/usdc-prime-usdc-morpho-gauntlet', destination: '/vault/usdc-prime-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-resolv-usdc-euler-apostro', destination: '/vault/usdc-resolv-euler-apostro-base', permanent: true },
      { source: '/vault/usdc-resolv-usdc-morpho-apostro', destination: '/vault/usdc-resolv-morpho-apostro-base', permanent: true },
      { source: '/vault/usdc-seamless-usdc-morpho-gauntlet', destination: '/vault/usdc-seamless-morpho-gauntlet-base', permanent: true },
      { source: '/vault/usdc-tulipa-euler-tulipa', destination: '/vault/usdc-tulipa-euler-bnb', permanent: true },
      { source: '/vault/usdc-turtle-avalanche-usdc-9summits-lagoon', destination: '/vault/usdc-turtle-avalanche-lagoon-9summits', permanent: true },
      { source: '/vault/usdc-ultrayield-usdc-morpho-edge-capital', destination: '/vault/usdc-ultrayield-morpho-edge-capital-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-cluster-euler-re7', destination: '/vault/usdc-cluster-euler-re7-avalanche', permanent: true },
      { source: '/vault/usdc-usdc-degen-morpho-hyperithm', destination: '/vault/usdc-degen-morpho-hyperithm-arbitrum', permanent: true },
      { source: '/vault/usdc-usdc-morpho-steakhouse', destination: '/vault/usdc-morpho-steakhouse-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-prime-morpho-gauntlet', destination: '/vault/usdc-prime-morpho-gauntlet-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-lagoon-syntropia', destination: '/vault/usdc-vault-lagoon-syntropia-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-august-digital', destination: '/vault/usdc-vault-morpho-august-digital-mainnet', permanent: true },
      { source: '/vault/usdc-usdc-vault-morpho-re7', destination: '/vault/usdc-vault-morpho-re7-mainnet', permanent: true },
      { source: '/vault/usdc-vault-bridge-usdc-morpho-steakhouse', destination: '/vault/usdc-vault-bridge-morpho-steakhouse-mainnet', permanent: true },
      { source: '/vault/usdc-wintermute-trading-private-credit-wildcat', destination: '/vault/usdc-wintermute-trading-private-credit-wildcat-mainnet', permanent: true },
      { source: '/vault/usdt-v3-aave', destination: '/vault/usdt-v3-aave-mainnet', permanent: true },

      // ── Dead products → hub page ──
      { source: '/vault/cbbtc-wintermute-trading-wildcat-mainnet', destination: '/cbbtc', permanent: true },
      { source: '/vault/usdt-clearstar-boring-morpho-ethereum', destination: '/usdt', permanent: true },

      // ── Wave 4 ──
      { source: '/vault/usdc-core-usdc-lagoon-detrade', destination: '/vault/usdc-core-lagoon-detrade-base', permanent: true },
    ];
  },
};

export default nextConfig;
